dist: trusty
sudo: required

env:
  global:
  - COMMIT=${TRAVIS_COMMIT::8}

install:
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends dotnet-dev-1.0.1
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs
  - sudo npm install semver -g

before_script:
  - chmod u+x build.sh
  - chmod u+x set-build-version.sh
  - eval $(./set-build-version.sh)
  - dotnet --info

script:
  - ./build.sh --version=$PROJECT_BUILD_VERSION --configuration=RELEASE --publish