language: csharp
env:
  - ARTIFACTS_PATHS=./artifacts
install:
  - DNX_VERSION="1.0.0-beta7"
  - curl -sSL https://raw.githubusercontent.com/aspnet/Home/dev/dnvminstall.sh | DNX_BRANCH=$DNX_VERSION sh && source ~/.dnx/dnvm/dnvm.sh && dnvm install $DNX_VERSION -a default
before_script:
  - chmod u+x build.sh
  - export TRAVIS_BUILD_NUMBER="0.1.0-beta.1.$TRAVIS_BUILD_NUMBER"
  - mono --version
  - dnu --version
  - bash -c "source ~/.dnx/dnvm/dnvm.sh"
  - dnvm list
script:
  - ./build.sh --buildNumber=$TRAVIS_BUILD_NUMBER --configuration=RELEASE --outputBasePath=./artifacts --pack
addons:
  artifacts: true
